name = "bitmap"
version = "0.1.0"
keywords = ["graphics", "image", "bitmap", "png"]
defaultTargets = ["Bitmap"]
testDriver = "bitmap_tests"

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "Bitmap"

[[lean_exe]]
name = "bitmap"
root = "BitmapMain"

[[lean_exe]]
name = "bitmap_tests"
root = "Bitmap.Tests"
